"""add check constraint enforcing positive position quantity

Revision ID: 7b057b2389a4
Revises: 2d94fb0fed51
Create Date: 2026-08-06 11:37:38.956801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b057b2389a4'
down_revision: Union[str, Sequence[str], None] = '2d94fb0fed51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_positions_quantity_positive', 'positions', 'quantity > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_positions_quantity_positive', 'positions', type_='check')
    # ### end Alembic commands ###
