"""initial schema

Revision ID: fa3e0a276845
Revises: 
Create Date: 2026-08-05 16:02:07.301645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3e0a276845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('first_available', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('model_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('lookback_window_days', sa.Integer(), nullable=False),
    sa.Column('mc_num_simulations', sa.Integer(), nullable=False),
    sa.Column('mc_random_seed', sa.Integer(), nullable=False),
    sa.Column('confidence_levels', sa.JSON(), nullable=False),
    sa.Column('extra_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('historical_start', sa.Date(), nullable=True),
    sa.Column('historical_end', sa.Date(), nullable=True),
    sa.Column('factor_shocks', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scenario_id'),
    sa.UniqueConstraint('name', 'version', name='uq_scenarios_name_version')
    )
    op.create_table('backtest_results',
    sa.Column('backtest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('num_observations', sa.Integer(), nullable=False),
    sa.Column('num_exceptions', sa.Integer(), nullable=False),
    sa.Column('kupiec_stat', sa.Float(), nullable=False),
    sa.Column('kupiec_pvalue', sa.Float(), nullable=False),
    sa.Column('kupiec_pass', sa.Boolean(), nullable=False),
    sa.Column('christoffersen_stat', sa.Float(), nullable=True),
    sa.Column('christoffersen_pvalue', sa.Float(), nullable=True),
    sa.Column('christoffersen_pass', sa.Boolean(), nullable=True),
    sa.Column('conditional_coverage_stat', sa.Float(), nullable=True),
    sa.Column('conditional_coverage_pvalue', sa.Float(), nullable=True),
    sa.Column('conditional_coverage_pass', sa.Boolean(), nullable=True),
    sa.Column('traffic_light_zone', sa.String(length=10), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['model_configs.config_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('backtest_id'),
    sa.UniqueConstraint('portfolio_id', 'config_id', 'window_start', 'window_end', 'method', name='uq_backtest_results')
    )
    op.create_index(op.f('ix_backtest_results_portfolio_id'), 'backtest_results', ['portfolio_id'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', 'as_of_date', name='uq_positions_portfolio_asset_date')
    )
    op.create_index(op.f('ix_positions_as_of_date'), 'positions', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_positions_asset_id'), 'positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('raw_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('asset_id', 'price_date', 'ingested_at', name='uq_prices_asset_date_ingested')
    )
    op.create_index(op.f('ix_prices_asset_id'), 'prices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_prices_price_date'), 'prices', ['price_date'], unique=False)
    op.create_table('returns',
    sa.Column('return_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('log_return', sa.Float(), nullable=False),
    sa.Column('simple_return', sa.Float(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('return_id'),
    sa.UniqueConstraint('asset_id', 'return_date', 'ingested_at', name='uq_returns_asset_date_ingested')
    )
    op.create_index(op.f('ix_returns_asset_id'), 'returns', ['asset_id'], unique=False)
    op.create_index(op.f('ix_returns_return_date'), 'returns', ['return_date'], unique=False)
    op.create_table('risk_runs',
    sa.Column('risk_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('data_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['model_configs.config_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('risk_run_id'),
    sa.UniqueConstraint('portfolio_id', 'as_of_date', 'config_id', name='uq_risk_runs')
    )
    op.create_index(op.f('ix_risk_runs_as_of_date'), 'risk_runs', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_risk_runs_portfolio_id'), 'risk_runs', ['portfolio_id'], unique=False)
    op.create_table('stress_results',
    sa.Column('stress_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('portfolio_pnl', sa.Float(), nullable=False),
    sa.Column('portfolio_pnl_pct', sa.Float(), nullable=False),
    sa.Column('position_contributions', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('stress_result_id'),
    sa.UniqueConstraint('portfolio_id', 'scenario_id', 'as_of_date', name='uq_stress_results')
    )
    op.create_index(op.f('ix_stress_results_portfolio_id'), 'stress_results', ['portfolio_id'], unique=False)
    op.create_table('backtest_exceptions',
    sa.Column('exception_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('var_forecast', sa.Float(), nullable=False),
    sa.Column('realised_return', sa.Float(), nullable=False),
    sa.Column('realised_pnl', sa.Float(), nullable=False),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_results.backtest_id'], ),
    sa.PrimaryKeyConstraint('exception_id'),
    sa.UniqueConstraint('backtest_id', 'as_of_date', name='uq_backtest_exceptions')
    )
    op.create_index(op.f('ix_backtest_exceptions_as_of_date'), 'backtest_exceptions', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_backtest_exceptions_backtest_id'), 'backtest_exceptions', ['backtest_id'], unique=False)
    op.create_table('cvar_results',
    sa.Column('cvar_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_run_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('cvar_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.risk_run_id'], ),
    sa.PrimaryKeyConstraint('cvar_result_id'),
    sa.UniqueConstraint('risk_run_id', 'method', 'confidence_level', name='uq_cvar_results')
    )
    op.create_index(op.f('ix_cvar_results_risk_run_id'), 'cvar_results', ['risk_run_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.risk_run_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_risk_run_id'), 'reports', ['risk_run_id'], unique=False)
    op.create_table('risk_decomposition',
    sa.Column('decomp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_run_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('component_var', sa.Float(), nullable=False),
    sa.Column('marginal_var', sa.Float(), nullable=False),
    sa.Column('pct_contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.risk_run_id'], ),
    sa.PrimaryKeyConstraint('decomp_id'),
    sa.UniqueConstraint('risk_run_id', 'asset_id', name='uq_risk_decomposition')
    )
    op.create_index(op.f('ix_risk_decomposition_risk_run_id'), 'risk_decomposition', ['risk_run_id'], unique=False)
    op.create_table('var_results',
    sa.Column('var_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_run_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('var_value', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_run_id'], ['risk_runs.risk_run_id'], ),
    sa.PrimaryKeyConstraint('var_result_id'),
    sa.UniqueConstraint('risk_run_id', 'method', 'confidence_level', name='uq_var_results')
    )
    op.create_index(op.f('ix_var_results_risk_run_id'), 'var_results', ['risk_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_var_results_risk_run_id'), table_name='var_results')
    op.drop_table('var_results')
    op.drop_index(op.f('ix_risk_decomposition_risk_run_id'), table_name='risk_decomposition')
    op.drop_table('risk_decomposition')
    op.drop_index(op.f('ix_reports_risk_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_cvar_results_risk_run_id'), table_name='cvar_results')
    op.drop_table('cvar_results')
    op.drop_index(op.f('ix_backtest_exceptions_backtest_id'), table_name='backtest_exceptions')
    op.drop_index(op.f('ix_backtest_exceptions_as_of_date'), table_name='backtest_exceptions')
    op.drop_table('backtest_exceptions')
    op.drop_index(op.f('ix_stress_results_portfolio_id'), table_name='stress_results')
    op.drop_table('stress_results')
    op.drop_index(op.f('ix_risk_runs_portfolio_id'), table_name='risk_runs')
    op.drop_index(op.f('ix_risk_runs_as_of_date'), table_name='risk_runs')
    op.drop_table('risk_runs')
    op.drop_index(op.f('ix_returns_return_date'), table_name='returns')
    op.drop_index(op.f('ix_returns_asset_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_prices_price_date'), table_name='prices')
    op.drop_index(op.f('ix_prices_asset_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_asset_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_as_of_date'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_backtest_results_portfolio_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_table('scenarios')
    op.drop_table('portfolios')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
